<a href="https://colab.research.google.com/github/Satya-1729/Python_machine_learning/blob/main/logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#code for logistics regression

import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

df = pd.read_csv("/content/train.csv")
df.head(10)

df.fillna(0, inplace = True)

x_train = df.iloc[:,[1,4]]
y_train = df.iloc[:,-1]

print(x_train,"\n\n\n\n")
print(y_train,"\n\n\n\n")

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
print(x_train,"\n\n\n\n")

# Reshape y_train to a 2D array with a single column
y_train = y_train.values.reshape(-1, 1)  # Reshape before scaling

y_train = scaler.fit_transform(y_train)
print(y_train,"\n\n\n\n")


def compute_logistic_cost(x,y,w,b):

  m = x.shape[0]
  cost = 0.0
  for i in range(m):
    z_i = np.dot(x[i],w) + b
    f_wb_i = sigmoid(z_i)
    cost += -y[i]*np.log(f_wb_i) - (1-y[i])*np.log(1-f_wb_i)

  cost = cost/m
  return cost

def sigmoid(z):
  g = 1/(1+np.exp(-z))
  return g

w_tmp = np.array([1,1])
b_tmp = -3
print(compute_logistic_cost(x_train,y_train,w_tmp,b_tmp))



      MSSubClass  LotArea
0             60     8450
1             20     9600
2             60    11250
3             70     9550
4             60    14260
...          ...      ...
1455          60     7917
1456          20    13175
1457          70     9042
1458          20     9717
1459          20     9937

[1460 rows x 2 columns] 




0       208500
1       181500
2       223500
3       140000
4       250000
         ...  
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64 




[[ 0.07337496 -0.20714171]
 [-0.87256276 -0.09188637]
 [ 0.07337496  0.07347998]
 ...
 [ 0.30985939 -0.14781027]
 [-0.87256276 -0.08016039]
 [-0.87256276 -0.05811155]] 




[[ 0.34727322]
 [ 0.00728832]
 [ 0.53615372]
 ...
 [ 1.07761115]
 [-0.48852299]
 [-0.42084081]] 




[-0.06054389]
Iteration 00.00: Cost [0.59224638]


<ipython-input-8-9d73e54887e3>:61: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dj_dw[j] = dj_dw[j] + err_i * x[i,j]


In [ ]:
def compute_gradient(x,y,w,b):

  m,n = x.shape
  dj_dw = np.zeros((n,))
  dj_db = 0.

  for i in range(m):
    f_wb_i = sigmoid(np.dot(x[i],w) + b)
    err_i = f_wb_i - y[i]
    for j in range(n):
      dj_dw[j] = dj_dw[j] + err_i * x[i,j]
    dj_db = dj_db + err_i

  dj_dw = dj_dw/m
  dj_db = dj_db/m

  return dj_dw,dj_db

def gradient_descent(x,y,w_in,b_in,alpha,num_iters):

  J_history = []
  w = w_in
  b = b_in

  for i in range(num_iters):
    dj_dw,dj_db = compute_gradient(x,y,w,b)

    w = w - alpha * dj_dw
    b = b - alpha * dj_db

    if i <100000:
      J_history.append(compute_logistic_cost(x,y,w,b))

    if i%math.ceil(num_iters/10) == 0:
      print(f"Iteration {i:5d}: Cost {J_history[-1].item():.2f}")

  return w,b,J_history

w_init = np.array([1,-1])
b_init = -2
alpha = 0.001
iters = 1000

w_final,b_final,J_hist = gradient_descent(x_train,y_train,w_init,b_init,alpha,iters)






<ipython-input-36-0a69d30aad1b>:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  dj_dw[j] = dj_dw[j] + err_i * x[i,j]


Iteration     0: Cost 0.59


KeyboardInterrupt: 

In [ ]:
print(predict)
print(y_train)

[0.12374692 0.05980584 0.1043015  ... 0.13959995 0.05935421 0.05851363]
[[ 0.34727322]
 [ 0.00728832]
 [ 0.53615372]
 ...
 [ 1.07761115]
 [-0.48852299]
 [-0.42084081]]


In [ ]:
print(f"\n\n w : {w_final}, b : {b_final.item():.2f}")



 w : [ 0.7593937  -0.68740814], b : -2.16


In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.